trigger:
- main

pool:
  name: Agent02

steps:

- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  displayName: init
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/to-do-infra'
    backendServiceArm: 'serviceconnection01'
    backendAzureRmResourceGroupName: 'vashu-rg'
    backendAzureRmStorageAccountName: 'vashu-stg'
    backendAzureRmContainerName: 'vashu-cont'
    backendAzureRmKey: 'terraform.tfstate'

- task: TerraformTask@5
  displayName: validate
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: '$(System.DefaultWorkingDirectory)/to-do-infra'

- task: TerraformTask@5
  displayName: plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/to-do-infra'
    environmentServiceNameAzureRM: 'serviceconnection01'

- task: TerraformTask@5
  displayName: apply
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/to-do-infra'
    commandOptions: '-auto-approve'
    environmentServiceNameAzureRM: 'serviceconnection01'